services:
  - type: web
    name: techforge-frontend
    env: node
    plan: free
    buildCommand: npm install && cd server && npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_GA_MEASUREMENT_ID
        value: G-RE8FYB41FC
      - key: EMAIL_USER
        value: techforge81@gmail.com
      - key: EMAIL_PASS